apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-server-mongodb-operator
spec:
  replicas: 1
  selector:
    matchLabels: {name: percona-server-mongodb-operator}
  template:
    metadata:
      labels: {name: percona-server-mongodb-operator}
    spec:
      containers:
      - command: [percona-server-mongodb-operator]
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef: {fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'}
        - {name: OPERATOR_NAME, value: percona-server-mongodb-operator}
        - {name: RESYNC_PERIOD, value: 5s}
        - {name: LOG_VERBOSE, value: 'false'}
        - name: POD_NAME
          valueFrom:
            fieldRef: {fieldPath: 'metadata.name'}
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: percona-server-mongodb-operator
        ports:
        - {containerPort: 60000, name: metrics}
        resources: {}
      serviceAccountName: percona-server-mongodb-operator
