apiVersion: psmdb.percona.com/v1-10-0
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  crVersion: 1.10.0
  image: >-
    build-harbor.alauda.cn/middleware/percona-server-mongodb:v4.2.17-mongodb
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  psmdbLogPath: ''
  secrets:
    users: my-cluster-name-secrets
  mongodbExporter:
    enabled: true
    image: build-harbor.alauda.cn/middleware/mongodb-exporter:v0.20.1-mongodb-exporter
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 200Mi
  mongod:
    net:
      port: 27017
      hostPort: 0
    security:
      redactClientLogData: false
      enableEncryption: true
      encryptionKeySecret: my-cluster-name-mongodb-encryption-key
      encryptionCipherMode: AES256-CBC
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 100
  replsets:
    - name: rs0
      size: 3
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      containerSecurityContext:
        runAsUser: 0
      podDisruptionBudget:
        maxUnavailable: 1
      podSecurityContext:
        fsGroup: 1001
      expose:
        enabled: false
        exposeType: NodePort
      arbiter:
        enabled: false
        size: 1
        affinity:
          antiAffinityTopologyKey: kubernetes.io/hostname
      resources:
        limits:
          cpu: 1000m
          memory: 2000Mi
        requests:
          cpu: 300m
          memory: 800Mi
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
  backup:
    containerSecurityContext:
      runAsUser: 0
    enabled: true
    restartOnFailure: true
    image: >-
      build-harbor.alauda.cn/middleware/percona-backup-mongodb:v1.3.4-mongodb-backup
    podSecurityContext:
      fsGroup: 1001
    serviceAccountName: percona-server-mongodb-operator
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
    storages: {}
    tasks: []
  sharding:
    enabled: false
    configsvrReplSet:
      size: 3
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: "300m"
          memory: "0.5G"
        requests:
          cpu: "300m"
          memory: "0.5G"
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    mongos:
      size: 3
      configuration: |
        systemLog:
           verbosity: 1
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: "300m"
          memory: "0.5G"
        requests:
          cpu: "300m"
          memory: "0.5G"
      expose:
        exposeType: ClusterIP
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: never
